const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        version: "1.0.0",
        title: "TRON SERVER API",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/api",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "contract",
            "description": "Endpoints"
        },
        {
            "name": "blockchain",
            "description": "Endpoints"
        },
        {
            "name": "transactions",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        }
    },
    definitions: {}
}

const outputFile = __dirname + '/../../storage/app/swagger_output.json';
const endpointsFiles = [__dirname + '/../routes/api/contract.api.js', __dirname + '/../routes/api/blockchain.api.js', __dirname + '/../routes/api/transactions.api.js', __dirname + '/../routes/api/index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    console.log('DONE');
}).catch((e) => {
    console.log(e);
});